### ISSUE TITLE
iPhoneのSKKにて設定をインポート出来ない

### ISSUE THREAD

**Issue by ghost** [shyazusa/skk#1]
iOS用SKK、FlickSKKの辞書インポート機能を使用してこれをインポートしようとするとエラーが出てくる。

**Comment by shyazusa** [comment]
調査してみるかー

**Comment by shyazusa** [comment]
形式が正しくないと言われちゃう謎……謎。

**Comment by shyazusa** [comment]
test用のテキストを作成してみたのだけれど、これでもダメだった……
https://github.com/shyazusa/skk/blob/master/test.txt

**Comment by shyazusa** [comment]
もう本家に聞きに行っちゃおうかな……
とりあえず今回ここでは改善させ(出来)ません。閉めます。
